version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql // Nome Do Container
    environment:
      MYSQL_ROOT_PASSWORD: root // SENHA DO BANCO DE DADOS
    ports:
      - "3306:3306"
    volumes:
        - will_data:/var/lib/mysql

volumes:
   will_data:
